### PR TITLE
Removed wheel version tag

### PR DESCRIPTION
**Pull request by moskey71**
Fixes # .

Changes offered/proposed in this pull request:
- 
- 
- 

* New PR Alert to: @plus3it/cfn

### CODE REVIEW

**Review by ferricoxide — COMMENTED** [review]
@moskey71  Nothing amiss, here: did you do a test-deployment to make sure this is all that's needed to fix the problem(s)?

**Comment by moskey71** [comment]
@ferricoxide testing out of band in AWS

**Review by ferricoxide — COMMENTED** [review]
Given that your `'pip<10'` and `setuptools` are taken care of in UserData, you can nuke them from the  `watchmaker-install` stanza

**Review by ferricoxide — APPROVED** [review]
Cool beans!

**Pull request merged**
